### ISSUE TITLE
vt++ not working for L2LDDISDV

### ISSUE THREAD

**Issue by samuelortion** [ObstinateM/vt-plus-plus#4]
Hi there,
I transmitted vt++ link on BioInfo discord server; and someone returns me an issue: there is no timetable render for L2LDDISDV.

Could it be the .ics link on VT that causes this issue ?

It is `l2dlisdv_informatique.ics` for this class.

**Comment by ObstinateM** [comment]
Okay, I'll add it tonight.
Thanks for reporting

**Comment by ObstinateM** [comment]
Okay it is fixed, I'll need someone to give me the relation between UE code and name please

**Comment by ObstinateM** [comment]
After some investigation, it looks like I can't fix the relation between UE code and name.
`UED311` is `BIOCHIMIE 1` and at the same time `PROBABILITES`, `UED312` is `BIOLOGIE MOLECULAIRE` and `THEORIE DES LANGAGES`.
Looks like some UE have the same code because the code is used in both licence.

Not sure that I can make this work without VT changing their ical
